#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HEAVEN_REPO == "heavenbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $HEAVEN_REPO == "heavenbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $HEAVEN_REPO =~ $regex ]]
    then
        if [[ $HEAVEN_REPO_BRANCH ]]
        then
            echo "${HEAVEN_REPO}/archive/${HEAVEN_REPO_BRANCH}.zip"
        else
            echo "${HEAVEN_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="heavenbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HEAVENPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HEAVENPATH
    echo "    Starting HEAVENBOT    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          ║║║║║╠╣║╔╝╔║║╣╠╣║╔╗║║║║║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
